/**
 * Archivo que contiene una lista extensa de maneras
 * en que un cliente podría solicitar o agendar un servicio.
 * 
 * Puedes usarlo para mejorar la detección de intenciones,
 * buscando coincidencias con estas frases o procesándolas
 * con un modelo de lenguaje.
 */

const intencionAgendarPhrases = [
 
    "agendar",
    "solicitar",
    "quiero ese servicio",
    "quiero eso",
    "Quiero solicitar una cita.",
    "Necesito agendar un servicio.",
    "¿Podemos programar una reunión?",
    "Deseo reservar mi turno.",
    "¿Podrías registrarme para el servicio?",
    "Me gustaría apartar una hora.",
    "¿Puedo coordinar una visita?",
    "Quiero separar un espacio en tu agenda.",
    "¿Sería posible fijar una cita contigo?",
    "Estoy interesado en agendar un servicio.",
    "Necesito apartar una cita.",
    "Deseo solicitar una reserva.",
    "¿Puedo programar una sesión?",
    "Me gustaría reservar una cita.",
    "Quiero agendar cuanto antes.",
    "Necesito que me aparten un horario.",
    "¿Tienes algún espacio disponible para mí?",
    "Solicito hora para el servicio, por favor.",
    "¿Me podrías anotar para la próxima fecha disponible?",
    "Requiero reservar un espacio.",
    "Quiero programar mi turno.",
    "Me gustaría enlistarme para el siguiente cupo.",
    "¿Puedo pedir una cita ahora mismo?",
    "Vengo a solicitar un turno para el servicio.",
    "Deseo que me agenden la próxima semana.",
    "Necesito reservar con anticipación.",
    "Estoy buscando reservar mi cita con usted.",
    "¿Cómo puedo apartar una hora contigo?",
    "Quiero confirmarte mi cita.",
    "¿Podrías programar el servicio para mí?",
    "Me gustaría arreglar una cita formal.",
    "Necesito coordinar mi reserva.",
    "¿Podríamos fijar un horario juntos?",
    "Solicito apuntarme para el servicio.",
    "Deseo concertar una reunión.",
    "¿Cómo reservo un espacio en la agenda?",
    "Quiero registrarme para tu servicio.",
    "¿Puedo reservar para el martes?",
    "Me interesa agendar ahora.",
    "Quisiera apartar un turno de inmediato.",
    "Necesito un turno cuanto antes.",
    "Quiero formalizar mi reserva.",
    "¿Existe la posibilidad de agendarme?",
    "Deseo confirmar mi horario de servicio.",
    "Me urge reservar una cita.",
    "¿Puedo gestionar una cita con usted?",
    "Quiero concretar el servicio.",
    "Solicito me reserven para la próxima fecha.",
    "Necesito asegurar un espacio en tu agenda.",
    "¿Me podrías ayudar a programar mi visita?",
    "¿Cómo puedo solicitar un turno para esta semana?",
    "Requiero fijar una reunión.",
    "Me gustaría separar una cita pronto.",
    "Por favor, aparta mi horario.",
    "¿Podemos dejar agendada la sesión de hoy?",
    "Deseo dejar confirmada mi cita.",
    "Necesito asegurar mi reservación.",
    "¿Cómo agendo el servicio con anticipación?",
    "Quiero pactar un servicio contigo.",
    "¿Podrías anotar mi nombre para el servicio?",
    "Me interesaría reservar un horario por la tarde.",
    "Necesito que me des un espacio en tu agenda.",
    "Deseo que me incluyas en el listado de citas.",
    "Quiero apartar mi lugar en la fila.",
    "¿Podríamos acordar una fecha para mi cita?",
    "Estoy buscando fijar una cita a la brevedad.",
    "Deseo agendar mi turno para mañana.",
    "¿Me podrías reservar un cupo?",
    "Necesito separar mi visita con tiempo.",
    "Quiero solicitar el servicio para la próxima semana.",
    "Quisiera dejar mi cita programada de inmediato.",
    "¿Cómo puedo oficializar mi reserva?",
    "Me gustaría que me pongas en la lista de espera.",
    "¿Hay manera de concretar una cita?",
    "Deseo coordinar un turno para el servicio.",
    "Necesito planificar el servicio contigo.",
    "Quiero inscribirme para la sesión.",
    "¿Podrías agendarme?",
    "Me urge programar una cita en tu agenda.",
    "Necesito reservar para hoy mismo, si se puede.",
    "Deseo fijar la fecha del servicio cuanto antes.",
    "¿Puedo hacer una reserva para el día de mañana?",
    "Quiero gestionar una cita formal contigo.",
    "¿Sería posible incluirme en tu agenda?",
    "Busco asignar un espacio en tu horario.",
    "Necesito acordar una sesión lo antes posible.",
    "Deseo concretar mi visita.",
    "Quisiera formalizar mi hora de servicio.",
    "¿Cómo reservo una cita con usted?",
    "Quiero ingresar mis datos para el turno.",
    "Me interesaría bloquear un horario en tu agenda.",
    "Necesito fijar un encuentro.",
    "Deseo obtener una reserva segura para el viernes.",
    "¿Podríamos programar una fecha en específico?",
    "Quiero separar mi turno ahora.",
    "Me gustaría llenar el formulario de agendamiento.",
    "Necesito agendar con urgencia.",
    "¿Puedo solicitar tu servicio para mañana en la tarde?",
    "Deseo dejar apartado mi cupo en tu lista.",
    "Quiero coordinar la cita mediante tu calendario.",
    "¿Podrías incluirme en tu programación?",
    "Quiero anotar mi nombre para el siguiente horario disponible.",
    "Deseo hacer una reserva con anticipación.",
    "Necesito apartar un espacio para esa fecha.",
    "¿Puedo programar una entrevista contigo?",
    "Quiero pedir mi turno formalmente.",
    "Solicito que me asignen un horario.",
    "Me gustaría que me confirmen la cita disponible.",
    "Necesito la próxima cita libre que tengas.",
    "Deseo tramitar mi reservación.",
    "¿Podríamos calendarizar esta cita?",
    "Quiero pactar una consulta.",
    "Me gustaría separar un turno a tu primera hora.",
    "Deseo coordinar la fecha exacta del servicio.",
    "¿Podrías bloquear un horario para mí?",
    "Necesito asegurar la próxima disponibilidad.",
    "Quiero reservar ya mismo.",
    "¿Puedo hacer una cita contigo para la próxima semana?",
    "Busco reservar tu primer horario del día.",
    "Deseo gestionar mi cita lo antes posible.",
    "Necesito un espacio a mediodía.",
    "Quiero confirmar el turno y la fecha ahora.",
    "¿Podemos dejar listo mi agendamiento?",
    "Me interesa reservar con urgencia.",
    "Deseo anotarme para el servicio de mañana.",
    "¿Tienes un espacio disponible para mí hoy?",
    "Necesito programar este servicio inmediatamente.",
    "Quiero separar mi cupo en línea.",
    "Solicito reservar tu próximo horario libre.",
    "Me gustaría que me agendes para el viernes.",
    "Deseo asegurar una cita antes del fin de semana.",
    "¿Me ayudas a reservar con fecha y hora?",
    "Necesito fijar mi visita en tu agenda.",
    "Quiero formalizar la cita de hoy.",
    "¿Cómo puedo reservar y asegurar mi espacio?",
    "Deseo apuntarme para la fecha más cercana.",
    "Necesito tramitar una reserva urgente.",
    "Quiero coordinar mi cita para el lunes.",
    "¿Existe disponibilidad para agendar mañana?",
    "Me gustaría reservar una sesión doble.",
    "Deseo consultar si puedo reservar para dos personas.",
    "Necesito programar mi cita vía telefónica.",
    "Quiero hacer una reservación en el horario de la tarde.",
    "¿Me anotas en tu calendario para la próxima semana?",
    "Solicito verificar si hay turnos libres hoy.",
    "Necesito confirmar mi cupo en la agenda.",
    "Deseo programar el servicio completo.",
    "¿Podemos acordar fecha y hora para mi cita?",
    "Quiero asegurar mi turno este mismo día.",
    "Me gustaría realizar la reserva oficial.",
    "Necesito un hueco en tu horario mañana.",
    "Quiero apuntarme para el servicio en cuanto se pueda.",
    "¿Puedes programarme para la próxima semana, por favor?",
    "Deseo concertar mi cita de forma inmediata.",
    "Necesito reservar una visita a tu oficina.",
    "Quiero organizar mi cita de antemano.",
    "¿Te queda algún espacio disponible para mí?",
    "Me interesaría establecer un horario fijo.",
    "Deseo formalizar el día y la hora de la cita.",
    "Necesito anotarme para la sesión siguiente.",
    "Quiero solicitar la cita a primera hora.",
    "¿Puedo reservar un cupo para hoy?",
    "Deseo pedir mi turno cuanto antes.",
    "Necesito dejar lista mi asistencia al servicio.",
    "Quiero concretar un horario específico.",
    "¿Podrías gestionar mi reserva en tu sistema?",
    "Me gustaría hacer un hueco en tu calendario.",
    "Necesito apartar un espacio seguro.",
    "Deseo obtener una cita confirmada para este mes.",
    "Quiero separar mi lugar en tu agenda cuanto antes.",
    "¿Podrías anotar mis datos para reservar?",
    "Solicito verificar qué horarios tienes libres.",
    "Necesito fijar una cita formal contigo.",
    "Deseo que me agenden lo antes posible.",
    "Quiero coordinar el horario para la próxima sesión.",
    "¿Cómo puedo registrarme para tu servicio?",
    "Me gustaría contar con un horario disponible pronto.",
    "Necesito reservar en la próxima hora libre que tengas.",
    "Deseo reservar mi cupo antes de que se llene.",
    "¿Puedo apartar una cita para esta misma tarde?",
    "Quiero solicitar el turno para mi nombre.",
    "Necesito asegurar que me atiendan mañana.",
    "Deseo oficializar mi reserva de inmediato.",
    "¿Quisieras programarme para el día de hoy?",
    "Quiero bloquear mi horario contigo.",
    "Me gustaría confirmar una cita sin falta.",
    "Necesito saber si puedo reservar por este medio.",
    "Deseo gestionar mi inscripción para el servicio.",
    "Quiero asegurarme un espacio la próxima semana.",
    "¿Podrías dejar mi cita agendada para el viernes?",
    "Necesito apartar un turno fijo en tu lista.",
    "Deseo tener mi reservación confirmada.",
    "Quiero garantizar mi cita lo antes posible.",
    "¿Me ayudas a programar una cita la próxima semana?",
    "Necesito dejar bloqueado un horario para mí.",
    "Deseo que me registres para la próxima sesión disponible.",
    "Quiero fijar esta cita y dejarla confirmada.",
    "¿Podrías verificar tu calendario y agendarme?",
    "Me gustaría apartar un cupo de urgencia.",
    "Necesito hacer la reserva y que quede confirmada."
  ];
  
  module.exports = {
    intencionAgendarPhrases
  };
  